# Generated by Django 3.2 on 2021-04-26 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_link',
            field=models.CharField(blank=True, default='kormev7gct', max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
