# Generated by Django 3.2 on 2021-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0002_auto_20210426_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_link',
            field=models.CharField(blank=True, default='f27aba', max_length=500, unique=True),
        ),
    ]
