# Generated by Django 3.2 on 2021-05-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_alter_url_short_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
