# Generated by Django 3.2 on 2021-05-06 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_url_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='title',
            field=models.CharField(default=uuid.uuid1, max_length=200, unique=True),
        ),
    ]
